[package]
name = "aura"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daggy = "0.8.0"
indextree = "4.5.0"
num-traits = "0.2.15"
